name: wedding_invitation_app
version: 1.0.0

environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.0.0
  google_fonts: ^6.3.0
  flutter_animate: ^4.5.0
  responsive_framework: ^0.1.0
  equatable: ^2.0.0
  dartz: ^0.10.0
  url_launcher: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
