name: wedding_invitation_app
version: 1.0.0

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.0.0
  google_fonts: ^2.1.0
  flutter_animate: ^1.0.0
  responsive_framework: ^0.1.0
  equatable: ^2.0.0
  dartz: ^0.10.0

flutter:
  uses-material-design: true
